alias ls=exa
alias cat=bat

export BAT_CONFIG_PATH="/root/.config/bat/bat.conf"
export GOPATH="/root/GOPATH"
export NODE_PATH=`yarn global dir`/node_modules:$NODE_PATH

export PATH=/root/bin:$PATH
export PATH=/root/.mix/escripts:$PATH
export PATH=$GOPATH/bin:$PATH
export PATH=`yarn global bin`:$PATH